### ISSUE TITLE
It doesn't change audience when modified on Credentials class

### ISSUE THREAD

**Issue by MarioRuiz** [googleapis/google-auth-library-ruby#256]
When supplying
```ruby
Google::Auth::Credentials.audience = "https://www.example.com"
auth = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open('./myfile.json'),
  scope: [my_scope])
p Google::Auth::Credentials.audience # returns example.com
p auth # returns https://www.googleapis.com/oauth2/v4/token
```

**Comment by dazuma** [comment]
This is expected behavior. Two reasons:

1. `Google::Auth::Credentials` is a base class, and when you set the `audience` field, you're only setting the default value. That default value doesn't change when you create instances of credentials elsewhere.
2. `Google::Auth::Credentials` is actually a different kind of thing than `Google::Auth::ServiceAccountCredentials`. The latter is _not_ a subclass of the former, and so making changes to one does not affect the other. (I know this is confusing. Unfortunately, `Google::Auth::Credentials` was moved here from a different gem some years ago, and we couldn't rename it without breaking things.)

**Comment by MarioRuiz** [comment]
Then how can we authenticate using a different audience?
