### ISSUE TITLE
Feature Request: Load default service account email in Compute Engine metadata environment

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-auth-library-ruby#270]
Hi,

Loading the default service account email from Compute Engine Metadata service would be helpful to help improve the experience when generating Signed URLs in Compute Engine using the Ruby Storage gem.

The default service account email in Compute Engine can be retrieved by calling:

```bash
curl -H "Metadata-Flavor: Google" 169.254.169.254:80/computeMetadata/v1/instance/service-accounts/default/email
```

This will help with autoloading the service account email which can then be used to generate valid signed URLs in compute engine instances.

Related issue: https://github.com/googleapis/google-cloud-ruby/issues/6268

Thank you for your consideration.

**Comment by shouichi** [comment]
@quartzmo In our case, the workaround you provided won't work because the abstraction library (ruby on rails active storage to be specific) won't allow us to pass email. This prevents us from migrating to workload identity. I assumed that migration from service account key to workload identity was transparent but it was not. It would be great if it is transparent as possible. Thanks!

**Comment by frankyn** [comment]
Thanks @quartzmo, I think [this](https://github.com/googleapis/google-auth-library-ruby/issues/270#issuecomment-934987654) is what we need to incorporate into google-cloud-storage https://github.com/googleapis/google-cloud-ruby/issues/13307.

Closing this FR in favor of the one in storage which should also address @shouichi's issue.
