### ISSUE TITLE
Default Service Account authentication on Cloud Run fails with `Signet::AuthorizationError - Unexpected error code 500trying to get security access token from Compute Engine metadata for the default service account` 

### ISSUE THREAD

**Issue by DavidS** [googleapis/google-auth-library-ruby#274]
#### Environment details

  - OS: https://hub.docker.com/layers/ruby/library/ruby/2.7/images/sha256-76d06f6815cd23f0758dbc8c04bc097db35ca400ecee17b8dcb1d8b548ee3b0e?context=explore
  - Ruby version:
  - Gem name and version: googleauth (0.13.1), google-cloud-firestore (2.3.0)

#### Steps to reproduce

  1. try to authenticate with firestore using the default service credential in a ruby process running under the default compute engine service account:

```ruby
firestore = Google::Cloud.firestore
job_ref = firestore.doc "jobs/#{job[:id]}"
job_ref.set job
```

the first line fails with
```
2020-10-02 10:31:32 - Signet::AuthorizationError - Unexpected error code 500trying to get security access token from Compute Engine metadata for
the default service account
:
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/compute_engine.rb:105:in `block in fetch_access_token'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/signet.rb:108:in `retry_with_error'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/compute_engine.rb:86:in `fetch_access_token'
/pvs/gems/gems/signet-0.14.0/lib/signet/oauth_2/client.rb:1054:in `fetch_access_token!'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/signet.rb:81:in `block in fetch_access_token!'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/signet.rb:108:in `retry_with_error'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/signet.rb:80:in `fetch_access_token!'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/credentials.rb:294:in `initialize'
/pvs/gems/gems/googleauth-0.13.1/lib/googleauth/credentials.rb:362:in `new'
...
```

Pinning to 0.13.0 or supplying a `scope: ['https://www.googleapis.com/auth/datastore']` or supplying a `project_id` to the firestore connection call all solved the problem, so I suspect #264  to be the culprit here. 

cc @ball-hayden

**Comment by alachaum** [comment]
We're seeing the same issue on our side. Downgrading to `0.13.0` fixed the issue.

**Comment by ball-hayden** [comment]
I'd added this support GKE's workload identity feature - I'm afraid I've no experience with Firestore.

I'm sorry it's caused issues, but I'm not able to help any further - the "magic" of the various uses of google meta server seems to be fairly poorly documented.

If the metadata service is 500ing, that sounds like a metadata service bug more than a client bug?

**Comment by alachaum** [comment]
The issue seems to impact all gcp gems (stackdriver, cloud tasks, pub/sub) when on Cloud Run. So I suspect this is a runtime issue.

Could it be that the metadata servers used from Cloud Run don't support the scope parameter?

I'll try to gather a bit more information to understand what's happening.

**Comment by DavidS** [comment]
> Could it be that the metadata servers used from Cloud Run don't support the scope parameter?

@alachaum since supplying a specific scope fixes the issue too, I don't think that's the issue - maybe the style of array encoding is different? I noticed that firestore has two default scopes.

**Comment by dazuma** [comment]
Opened #277 which should fix this. It looks like the metadata server generally expects comma-delimited scopes instead of space-delimited. Sorry for not catching that when I reviewed #264.

**Comment by dazuma** [comment]
@ball-hayden The only place I could find was the [GKE metadata server documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gke_mds) which explicitly says to use commas. Nominally, the metadata servers are supposed to be mutually compatible inasmuch as their keys overlap (although some are subsets because some keys may not make sense in some environments). However, passing `scopes` as a query param is an extension that wasn't part of the original [compute metadata service](https://cloud.google.com/compute/docs/storing-retrieving-metadata) and it doesn't seem to be documented well everywhere it is supported. I had to go through and test it in other environments such as Cloud Run.
