### ISSUE TITLE
Bearer prefix in jwt_token

### ISSUE THREAD

**Issue by alexkravets** [googleapis/google-auth-library-ruby#60]
Not sure if this is an issue of auth library, but token generated here:

https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/service_account.rb#L171

conflicts with gapi JS library if passed as is:

``` coffeescript
gapi.analytics.auth.authorize
  serverAuth:
    access_token: accessToken
```

The problem is that `Bearer` prefix is added once again by `gapi` method. Is this `gapi` issue, that might need to check if token contains `Bearer` prefix before adding one?

**Comment by sqrrrl** [comment]
Not really a bug in either. apply!() is intended to augment a hash of HTTP headers. It's doing that correctly and building a valid authorization header.

And in the gapi case, it's expecting a raw token, not a full header. Passing one to the other without adapting is, as you realized, a bug.

It's a reasonable feature request to make new_jwt_token public for cases where you just want the token and nothing else. Otherwise, just strip the 'Bearer ' prefix yourself.

**Comment by alexkravets** [comment]
Thanks!

Yes, I agree with all your points.

For me the problem here was that it's tricky to figure out `Bearer` problem to make `gapi` and `google-auth-library-ruby` work together. Deep dive into implementation details was required. So adding an extra interface method for pulling just token without `Bearer` and headers assumption would make a big difference.

I've bumped into this issue cause latest version `google-api-ruby-client` now forces to use `google-auth-library-ruby`. In my case we're pulling GA charts into CMS.

**Comment by dalehamel** [comment]
I came across this issue when reading https://cloud.google.com/run/docs/authenticating/end-users and was a bit surprised that ruby lacks the support to verify these tokens, where other languages have support for this.

until such support is available, I guess implementing a minimal API based on https://developers.google.com/identity/sign-in/web/backend-auth?#verify-the-integrity-of-the-id-token is the way to go?
